#! /bin/sh

### BEGIN INIT INFO
# Provides:          zulip-to-irc
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This will launch a bot for transporting between IRC and Zulip
# Description:       
### END INIT INFO

# get config info
. /srv/git/zulip-irc-ii/zulip-to-irc.conf

start_zulip_to_irc() {
	# start ii first
	/sbin/start-stop-daemon \
		--start \
		--chuid "$z3i_user:$z3i_group" \
		--background \
		--pidfile "$ii_pid_path" \
		--make-pidfile \
		--exec "$path_to_ii" -- \
			-s "$irc_network" \
			-p "$irc_port" \
			-i "$ii_target" \
			-n "$bot_name" -f "$bot_name"
	if [ $? -ne 0 ]; then
		echo "ii is already running"
		exit 1
	fi
	# join the channel, takes a second to get up
	sleep 2
	if [ -p "$ii_target/$irc_network/in" ]; then
		echo "/j $ii_channel" > "$ii_target/$irc_network/in"
	else
		echo "Tried to join a network too quickly. Sorry for the lazy sleep, giving up"
		exit 1;
	fi
	# start zulip-irc-ii
	"$path_to_zulip_irc" \
		-f "$zulip_rc" \
		-d "$ii_target/$irc_network/$ii_channel/" \
		-n "$your_irc_nick" \
		-u "$z3i_user" \
		-g "$z3i_group" \
		-p "$zulip_irc_ii_pid_path" \
		-t "$zulip_irc_translations" \
		-l "$zulip_irc_log_path" 
	
	if [ $? -ne 0 ]; then
		echo "Couldn't start zulip-irc-ii"
		exit 1
	fi
}

stop_zulip_to_irc() {
	# stop ii
    /sbin/start-stop-daemon \
        --stop \
		--quiet \
        --pidfile "$ii_pid_path"

    if [ $? -ne 0 ]; then
        echo "ii is already dead, hunting for zulip-irc-ii"
    fi

    # check if zulip-ii-irc is running
	start-stop-daemon --status --pidfile "$zulip_irc_ii_pid_path"
	if [ $? -ne 0 ]; then
		echo "Zulip-irc-ii is already dead"
	else 
		# kill the process group
		kill -INT -$(cat $zulip_irc_ii_pid_path)
	fi
}

case "$1" in
  start)
    echo "Starting zulip-to-irc"
	start_zulip_to_irc
    ;;
  stop)
    echo "Stopping zulip-to-irc"
	stop_zulip_to_irc
    ;;
  restart)
	echo "Restarting zulip-to-irc"
	stop_zulip_to_irc
	echo "zulip-to-irc stopped..."
	start_zulip_to_irc
	echo "zulip-to-irc started again"
	;;
  status)
  	start-stop-daemon --status --pidfile "$ii_pid_path"
	if [ $? -eq 0 ]; then
		echo "ii is running"
	else
		echo "ii is not running"
	fi
	start-stop-daemon --status --pidfile "$zulip_irc_ii_pid_path"
	if [ $? -eq 0 ]; then
		echo "zulip-irc-ii is running"
	else
		echo "zulip-irc-ii is not running"
	fi
	;;
  *)
    echo "Usage: /etc/init.d/zulip-to-irc {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
